import "./globals.css";
import localFont from "next/font/local";
import { Open_Sans, Montserrat } from "next/font/google";
import Providers from "@/components/Providers";
import LayoutProvider from "@/components/LayoutProvider";

const OPTIAmway = localFont({
  src: [
    {
      path: "../../public/fonts/OPTIAmway.ttf.woff",
    },
  ],
  variable: "--font-opt",
});

const opensans = Montserrat({
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${opensans.className} antialiased `}>
      <body>
        <Providers>
          <LayoutProvider>{children}</LayoutProvider>
        </Providers>
      </body>
    </html>
  );
}
