import "./globals.css";
import localFont from "next/font/local";
import Navbar from "@/components/Navbar";
import Providers from "@/components/Providers";

const OPTIAmway = localFont({
  src: [
    {
      path: "../../public/fonts/OPTIAmway.ttf.woff",
    },
  ],
  variable: "--font-opt",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${OPTIAmway.variable} antialiased `}>
      <body>
        <Providers>
          <div className="px-4 sm:px-8 md:px-16 xl:px-32 text-dark bg-light dark:bg-dark dark:text-light min-h-screen w-full ">
            <Navbar />
            {children}
          </div>
        </Providers>
      </body>
    </html>
  );
}
